baseURL = "http://rsangole.github.io/"
languageCode = "en-us"
title = "Rahul Sangole"
theme = "minimal"
disqusShortname = "rsangole-netlify-com" # delete this to disable disqus comments
googleAnalytics = "UA-106573867-1"
toc = "true"

[params]
    author = "Rahul sangole"
    description = "hacking my way through stats and ml"
    githubUsername = "rsangole"
    accent = "gray"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "vs"
    highlightLanguages = ["r"]
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjslang = ["r"]

[[menu.main]]
    url = "/"
    name = "~/home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "~/posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "~/projects"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "~/tags"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:rahul.sangole@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rsangole/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/rsangole/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/rahulsangole/"
    name = "linkedin"
    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/rsangole/"
#    name = "stack-overflow"
#    weight = 5
